export const endpoints = {
  INVALID_REFRESH_TOKEN: "/api/account/token/refresh",
  POST_ACCOUNT_REGISTRATION_FARMER: "/api/account/registration/farmer",
  POST_ACCOUNT_REGISTRATION_POLICY_MAKER: "/api/account/registration/policy-maker",
  POST_ACCOUNT_LOGIN: "/api/account/login",
  GET_MANDALS: "/api/mandals",
  GET_FARMER: "/api/farmer",
  GET_FARMER_DETAIL: "/api/farmer/:id",
  GET_PRODUCTION_DATA: "/api/farmer/:id/farm/production-data",
  GET_FARMER_NOTE: "/api/farmer/:id/note",
  GET_FARMER_REQUESTS: "/api/requests/?RequestCreatedById=:id",
  POST_FARMER_NOTE: "/api/farmer/:id/note",
  GET_PROBLEM_TYPE: "/api/problem-type",
  DELETE_ACCOUNT: "/api/account/:id",
  GET_PRODUCTION_TYPES: "/api/farmer/farm/production-data/production-types",
  POST_PRODUCTION_DATA: "/api/farmer/farm/production-data",
  PUT_PRODUCTION_DATA: "/api/farmer/farm/production-data/:id",
}