/**
 * This files contains all the strings and texts used in the project.
 * Texts were extracted for easier translation and management.
 */
const strings = {
  LOG_IN: "Log in",
  DELETE_ACCOUNT: "Delete Account",
  HOME: "Home",
  CREATE_ACCOUNT: "Create account",
  SIGN_OUT: "Sign out",
  DREAM: "DREAM",
  DREAM_SHORT_DESCRIPTION: "Data-dRiven PrEdictive FArMing in Telangana",
  DREAM_DESCRIPTION: "DREAM is a project that intends to redesign the food production process in the Telangana area in order to create more resilient agricultural systems that will be required to meet the region’s rising food demand.",
  DREAM_IMAGE_FARM: "Farm picture",
  DREAM_GOAL: "The goal is to help Telangana’s government promote data-driven policy-making in the state by designing, developing, and demonstrating anticipatory governance models for food systems utilizing digital public goods and community-centric approaches. The system aims to enable policy makers to identify farmers who perform well, especially under tough weather conditions, farmers who perform particularly badly and require assistance, and understand if agronomist-led steering initiatives yield substantial outcomes. This is going to be achieved by continuous assessment based on the visualizations of the acquired data.",
  DREAM_GOAL_LABEL: "Our goal",
  SUBMIT: "Submit",
  SAVE_CHANGES: "Save changes",
  ADD: "Add",
  EDIT: "Edit",
  REMIND_PASSWORD: "Remind password",
  DASHBOARD: "Dashboard",
  CHANGE: "Change",
  CHANGE_NOTE: "Change note",
  CREATE_HELP_REQUEST: "Create help request",
  CREATE_FORUM: "Create forum thread",
  HELP_REQUEST: "Help request",
  ADVICE: "Advice",
  NOTE: {
    NEGATIVE: "Negative",
    NEUTRAL: "Neutral",
    POSITIVE: "Positive"
  },
  ROLE: {
    FARMER: "Farmer",
    POLICY_MAKER: "Policy maker",
  },
  SIDEBAR: {
    SUMMARY: "Summary",
    PRODUCTION_DATA: "Production data",
    MY_HELP_REQUESTS: "My help requests",
    PROVIDE_HELP: "Provide help",
    FORUM: "Forum",
    FARMERS: "Farmers",
  },
  FORM: {
    LABEL: {
      NAME: "Name",
      SURNAME: "Surname",
      EMAIL: "E-mail",
      ROLE: "Role",
      PASSWORD: "Password",
      SENSOR_SYSTEM_ID: "Sensor ID",
      WATER_IRRIGATION_ID: "Water irr. ID",
      ADDRESS_LINE_1: "Address line 1",
      ADDRESS_LINE_2: "Address line 2",
      CONFIRM_PASSWORD: "Confirm password",
      POSTAL_CODE: "Postal code",
      CITY: "City",
      MANDAL: "Mandal",
      MANDALS: "Mandals",
      ADD_MANDALS: "Add mandals",
      ADD_PRODUCTION_DATA: "Add production data",
      MANAGE_PRODUCTION_DATA: "Manage production data",
      REMIND_PASSWORD: "Please enter the e-mail address associated with your account.",
      TOPIC: "Topic",
      DESCRIPTION: "Description",
      MESSAGE_CONTENT: "Write content of your message here",
      TYPE: "Type",
      AMOUNT: "Amount",
      DATE: "Date",
      ACTION: "Action",
      PROBLEM_TYPE: "Problem type",
      NOTE: "Note",
    },
    ERROR: {
      EMAIL_INCORRECT_FORMAT: "Provided email has incorrect format",
      PASSWORD_INCORRECT_FORMAT: "Provided password is too short",
      PASSWORD_DO_NOT_MATCH: "The two passwords that you entered do not match",
      REQUIRED: "This field is required"
    },
  },
  INFO: {
    ACCOUNT_CREATED: "Account created successfully.",
    ACCOUNT_DELETED: "Account deleted successfully.",
    NOTE_SAVED: "Note saved.",
    PRODUCTION_DATA_DELETED: "Production data deleted.",
  },
  ERROR: {
    NO_AUTHORIZED_403: "You don't have permissions to perform this action.",
    NOT_FOUND_404: "Resource not found.",
    SERVER_ERROR_500: "Server error occurred.",
    CHILL_FOR_A_MOMENT_429: "You made too many requests. Try again later.",
    UNIDENTIFIED_ERROR: "An unidentified error occurred."
  },
  WARNING: {
    DELETE_ACCOUNT: "If you are sure that you want to delete your account, provide again your password and click Submit.",
    LOGOUT: "You were logged out.",
  },
  RETURN_HOME: "Return home!",
}
export default strings