@startuml Assess farmer's performence

mainframe Assess farmer's performance
autonumber

actor "Policy maker" as PolMaker
participant DREAM

PolMaker -> DREAM++: Get all farmers
DREAM --> PolMaker--: Display a list of farmers

PolMaker -> DREAM++: Pick a farmer
DREAM --> PolMaker--: Display the farmer's summary

opt Assess farmer's performance
    PolMaker -> DREAM++: Assign a new note
    DREAM -> DREAM++: Update the farmer's note
    deactivate DREAM

    alt operation successful
        DREAM --> PolMaker : Display the farmer's summary
    else operation failed
        DREAM --> PolMaker--: Display error message
    end
end

@enduml
