@startuml Create Account 

mainframe Create account
autonumber

actor "Unregistered user" as Unreg
participant "User interface" as UI
participant Backend
database Database as DB

Unreg -> UI : Click on create account
UI --> Unreg : Display registration form

Unreg -> UI : Provide registration data
UI -> Backend : Validate data

alt data correct
    alt userType == Agronomist
        Backend -> DB : Create new agronomist
    else userType == Farmer
        Backend -> DB : Create new farm
        Backend -> DB : Create new farmer
    else userType == PolicyMaker
        Backend -> DB : Create new policy maker
    end

    DB --> Backend : Operation response

    alt operation successful
        Backend -> UI : Success
        UI --> Unreg : Display success message
    else operation failed
        Backend -> UI : Error
        UI --> Unreg : Display error message
    end
else data incorrect
    Backend --> UI : Error
    UI --> Unreg : Display error message
end

@enduml
