@startuml Request help

mainframe Request help
autonumber

actor Farmer
participant DREAM

Farmer -> DREAM++: Request help
DREAM --> Farmer--: Show help request creation form

Farmer -> DREAM++: Provide topic and contents of the message
DREAM -> DREAM++: Create help request
deactivate DREAM

alt operation successful
    DREAM --> Farmer : Display the request created
else operation failed
    DREAM --> Farmer--: Show error message
end

@enduml
