@startuml State

mainframe Visit a farm
hide empty description

left to right direction

state Planned
state Confirmed
state Rejected

[*] --> Planned : Plan a visit
Planned --> Planned : Replan a visit\n[today < visit->date]
Planned --> Confirmed : Confirm the visit\n[today >= visit->date]
Planned --> Rejected : Reject the visit\n[today >= visit->date]
Planned --> Rejected : Delete the visit\n[today < visit->date]

Rejected --> [*]
Confirmed --> [*]

@enduml