@startuml Use case
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

' skinparam linetype polyline
' skinparam linetype ortho

'Primary - should be on the left side
actor :Unregistered user: as UnregUser

package RegisteredUser {
    actor :Policy maker: as PolMaker
    actor :Farmer:
    actor :Agronomist:
}

' 'Secondary - should be on the right side
' package ExternalSystem {
'     actor :WeatherForecastSystem:
'     actor :WaterIrrigationSystem:
'     actor :SensorSystem:
' }

'visualisations - less details or additional phenomenas? as in lower diagram
'there are MANY missing phenomenas, that can be deducted from UC
'about SP: which is better?? - maybe a question to tamburri
'   "The system visualizes data ... for argonomist"
'   "The system visualizes data ..."
'   "Agronomist visualizes data"
rectangle DREAM {
    '''''''''''Common'''''''''''
    RegisteredUser -- (Log in)
    RegisteredUser -- (Reset password)
    RegisteredUser -- (Delete account)
    UnregUser -- (Create account)
    ' PolMaker -- (Log in)
    ' Agronomist -- (Log in)
    (Create account) ..> (Insert role specific data) : <<include>>

    '''''''''''Farmer'''''''''''
    ' Farmer -- (Log in)
    Farmer -- (Visualize relevant data)
    'should providers be included? maybe a question to Tamburri
    (Visualize relevant data) ..> (Visualize farm data) : <<include>>
    (Visualize farm data) ..> (Get information about weather forecasts) : <<include>>
    (Visualize farm data) ..> (Get information about soil humidity) : <<include>>
    (Visualize farm data) ..> (Get information about water usage) : <<include>>
    (Visualize relevant data) ..> (Display personal suggestions) : <<include>>
    Farmer -- (Manage production data)
    Farmer -- (Request help)
    Farmer -- (View forum)
    (View forum) <.. (Create forum thread) : <<extend>>
    (View forum) <.. (View forum thread) : <<extend>>
    (View forum thread) <.. (Delete forum comment) : <<extend>>
    (View forum thread) <.. (Add forum comment) : <<extend>>
    Farmer -- (View list of requests)
    Farmer -- (View list of my requests)
    (View list of my requests) <.. (Create request) : <<extend>>
    (View list of my requests) <.. (View my request) : <<extend>>
    (View my request) <. (Delete request) : <<extend>>

    '''''''''''Agronomist'''''''''''
    Agronomist -- (View farmer's summary)
    Agronomist -- (View list of requests)
    (View list of requests) <.. (View request) : <<extend>>
    (View request) <.. (Create response) : <<extend>>
    (View request) <.. (Delete response) : <<extend>>
    (View farmer's summary) ..> (Visualize farm data) : <<include>>
    Agronomist -- (View daily plan)
    (View daily plan) <.. (Manage daily plan) : <<extend>>
    (View daily plan) <.. (Set daily plan execution state) : <<extend>>
    (Set daily plan execution state) .> (Save comment regarding farm visit) : <<include>>

    '''''''''''Policy maker'''''''''''
    PolMaker -- (Assess farmer's performance)
    (Assess farmer's performance) ..> (View farmer's summary) : <<include>>
}

@enduml
