FARMERS_WITH_NEGATIVE_NOTE_LABEL = 'Farmers | Negative note'
FARMERS_WITH_POSITIVE_NOTE_LABEL = 'Farmers | Positive note'
MY_HELP_REQUESTS_LABEL = 'My help requests'
PRODUCTION_DATA_LABEL = 'Production data'
RECENT_PRODUCTION_DATA_LABEL = 'Recent production data'
SOIL_HUMIDITY_LABEL = 'Average soil humidity'
SUMMARY_LABEL = 'Summary'
TIPS_AND_SUGGESTIONS_LABEL = 'Tips & Suggestions'
WATER_USAGE_LABEL = 'Water usage'
WEATHER_FORECAST_LABEL = 'Weather'

INVALID_EMAIL = 'Provided email has incorrect format'
FIELD_IS_REQUIRED_WARNING = 'This field is required'
