DO $$
BEGIN
IF NOT EXISTS (
        SELECT * FROM "Suggestions"
    ) THEN
    INSERT INTO "Suggestions" ("Text", "MandalId", "ProductionTypeId") 
        VALUES 
        ('Invest in cold tolerant varieties.', 4, 12),
        ('Consider focusing on planting red gram.', 28, 14),
        ('Consider using nitrogen.', 24, 20),
        ('Think about utilizing interplanting.', 18, 14),
        ('Invest in heat tolerant varieties.', 8, 24),
        ('Think about utilizing interplanting.', 14, 10),
        ('Consider using nitrogen.', 1, 15),
        ('Consider using nitrogen.', 21, 20),
        ('Increase the level of irrigation.', 19, 3),
        ('Decrease the level of irrigation.', 32, 22),
        ('Consider focusing on planting red gram.', 25, 7),
        ('Consider focusing on planting black gram.', 20, 9),
        ('Consider focusing on planting castor.', 13, 11),
        ('Consider focusing on groundnut.', 20, 20),
        ('Consider using nitrogen.', 24, 20),
        ('Consider using nitrogen.', 33, 11),
        ('Consider focusing on planting soyabean.', 33, 5),
        ('Consider focusing on planting green gram.', 24, 5),
        ('Consider focusing on planting green gram.', 13, 3),
        ('Consider focusing on planting green gram.', 31, 3),
        ('Consider focusing on planting sesame.', 12, 12),
        ('Consider focusing on planting castor.', 19, 24),
        ('Consider focusing on planting castor.', 12, 18),
        ('Decrease the level of irrigation.', 17, 12),
        ('Decrease the level of irrigation.', 27, 13),
        ('Invest in cold tolerant varieties.', 32, 6),
        ('Consider focusing on planting castor.', 6, 19),
        ('Consider focusing on planting sorghum.', 6, 9),
        ('Consider focusing on planting rice.', 5, 8),
        ('Consider focusing on planting green gram.', 8, 21),
        ('Consider focusing on planting red gram.', 3, 19),
        ('Consider focusing on groundnut.', 31, 20),
        ('Consider focusing on planting sesame.', 25, 8),
        ('Consider focusing on planting cotton.', 6, 5),
        ('Consider focusing on planting sorghum.', 33, 5),
        ('Consider focusing on planting soyabean.', 22, 1),
        ('Consider focusing on planting sorghum.', 28, 4),
        ('Consider focusing on planting cotton.', 29, 17),
        ('Consider focusing on planting red gram.', 20, 19),
        ('Invest in cold tolerant varieties.', 6, 1),
        ('Consider focusing on planting corn.', 6, 1),
        ('Consider focusing on planting black gram.', 3, 19),
        ('Consider using biofertilizers.', 24, 15),
        ('Consider focusing on planting soyabean.', 20, 7),
        ('Consider focusing on planting sesame.', 11, 19),
        ('Consider using nitrogen.', 13, 4),
        ('Consider focusing on planting sesame.', 18, 20),
        ('Consider focusing on planting corn.', 21, 9),
        ('Consider focusing on planting green gram.', 2, 14),
        ('Consider using nitrogen.', 28, 14),
        ('Consider focusing on planting black gram.', 6, 17),
        ('Decrease the level of irrigation.', 24, 2),
        ('Consider focusing on planting black gram.', 30, 21),
        ('Consider focusing on planting rice.', 27, 3),
        ('Consider focusing on planting sorghum.', 20, 2),
        ('Invest in heat tolerant varieties.', 26, 24),
        ('Consider focusing on planting rice.', 2, 15),
        ('Invest in cold tolerant varieties.', 11, 17),
        ('Consider focusing on planting sorghum.', 10, 13),
        ('Decrease the level of irrigation.', 22, 5),
        ('Consider focusing on planting cotton.', 22, 11),
        ('Invest in heat tolerant varieties.', 31, 5),
        ('Consider using biofertilizers.', 19, 18),
        ('Consider focusing on planting black gram.', 25, 3),
        ('Consider focusing on planting green gram.', 29, 3),
        ('Invest in heat tolerant varieties.', 15, 13),
        ('Invest in heat tolerant varieties.', 2, 10),
        ('Consider focusing on planting cotton.', 27, 22),
        ('Consider focusing on planting sesame.', 16, 18),
        ('Decrease the level of irrigation.', 6, 9),
        ('Increase the level of irrigation.', 27, 18),
        ('Invest in cold tolerant varieties.', 16, 11),
        ('Consider focusing on planting castor.', 27, 18),
        ('Decrease the level of irrigation.', 32, 5),
        ('Consider focusing on planting sorghum.', 33, 16),
        ('Invest in cold tolerant varieties.', 10, 5),
        ('Consider focusing on planting cotton.', 27, 21),
        ('Consider using biofertilizers.', 3, 7),
        ('Consider focusing on planting soyabean.', 17, 23),
        ('Consider using nitrogen.', 18, 13),
        ('Consider focusing on planting sesame.', 22, 18),
        ('Decrease the level of irrigation.', 3, 22),
        ('Invest in heat tolerant varieties.', 19, 4),
        ('Consider focusing on planting soyabean.', 20, 19),
        ('Consider using nitrogen.', 17, 15),
        ('Decrease the level of irrigation.', 26, 21),
        ('Invest in cold tolerant varieties.', 8, 2),
        ('Consider focusing on planting corn.', 33, 4),
        ('Consider focusing on planting green gram.', 25, 8),
        ('Consider focusing on planting sesame.', 16, 2),
        ('Consider focusing on planting corn.', 28, 3),
        ('Consider focusing on planting castor.', 26, 13),
        ('Consider focusing on planting corn.', 4, 19),
        ('Consider focusing on planting black gram.', 25, 2),
        ('Invest in heat tolerant varieties.', 24, 18),
        ('Decrease the level of irrigation.', 29, 14),
        ('Consider focusing on planting castor.', 21, 8),
        ('Consider focusing on planting black gram.', 32, 23),
        ('Consider focusing on planting cotton.', 30, 20),
        ('Consider focusing on planting sorghum.', 28, 10),
        ('Consider focusing on planting green gram.', 10, 14),
        ('Consider using biofertilizers.', 19, 18),
        ('Increase the level of irrigation.', 11, 1),
        ('Consider focusing on planting corn.', 18, 15),
        ('Invest in cold tolerant varieties.', 25, 9),
        ('Consider focusing on planting cotton.', 26, 6),
        ('Consider focusing on groundnut.', 32, 5),
        ('Consider using nitrogen.', 23, 20),
        ('Decrease the level of irrigation.', 26, 16),
        ('Invest in heat tolerant varieties.', 12, 21),
        ('Consider focusing on planting castor.', 15, 9),
        ('Think about utilizing interplanting.', 22, 7),
        ('Consider using nitrogen.', 27, 2),
        ('Consider focusing on planting soyabean.', 24, 9),
        ('Consider focusing on planting soyabean.', 8, 24),
        ('Consider focusing on planting green gram.', 6, 3),
        ('Increase the level of irrigation.', 8, 17),
        ('Consider focusing on planting sorghum.', 16, 20),
        ('Consider using biofertilizers.', 21, 1),
        ('Consider using nitrogen.', 33, 11),
        ('Invest in cold tolerant varieties.', 7, 7),
        ('Consider focusing on groundnut.', 9, 3),
        ('Invest in heat tolerant varieties.', 4, 22),
        ('Decrease the level of irrigation.', 5, 14),
        ('Invest in heat tolerant varieties.', 29, 4),
        ('Increase the level of irrigation.', 4, 16),
        ('Think about utilizing interplanting.', 16, 6),
        ('Invest in cold tolerant varieties.', 29, 21),
        ('Increase the level of irrigation.', 30, 20),
        ('Consider focusing on groundnut.', 29, 21),
        ('Increase the level of irrigation.', 14, 18),
        ('Consider focusing on planting green gram.', 3, 2),
        ('Consider focusing on planting sesame.', 33, 20),
        ('Consider focusing on planting sesame.', 27, 4),
        ('Consider focusing on groundnut.', 27, 2),
        ('Consider using nitrogen.', 31, 3),
        ('Invest in cold tolerant varieties.', 10, 5),
        ('Invest in heat tolerant varieties.', 19, 21),
        ('Invest in heat tolerant varieties.', 14, 6),
        ('Consider using biofertilizers.', 7, 10),
        ('Consider focusing on planting red gram.', 27, 13),
        ('Consider focusing on planting black gram.', 23, 11),
        ('Consider focusing on groundnut.', 26, 24),
        ('Decrease the level of irrigation.', 28, 11),
        ('Invest in cold tolerant varieties.', 3, 23),
        ('Consider focusing on planting red gram.', 10, 3),
        ('Consider focusing on planting cotton.', 4, 11),
        ('Invest in cold tolerant varieties.', 10, 22),
        ('Consider focusing on groundnut.', 22, 2),
        ('Consider focusing on planting soyabean.', 23, 15),
        ('Think about utilizing interplanting.', 32, 7),
        ('Invest in heat tolerant varieties.', 18, 23),
        ('Consider focusing on groundnut.', 12, 7),
        ('Invest in cold tolerant varieties.', 24, 14),
        ('Invest in heat tolerant varieties.', 9, 3),
        ('Consider focusing on planting soyabean.', 4, 8),
        ('Consider focusing on planting red gram.', 24, 16),
        ('Consider focusing on planting corn.', 19, 22),
        ('Consider focusing on planting castor.', 1, 4),
        ('Consider using biofertilizers.', 9, 22),
        ('Consider focusing on planting green gram.', 3, 8),
        ('Consider using nitrogen.', 12, 3),
        ('Invest in heat tolerant varieties.', 18, 6),
        ('Consider focusing on planting red gram.', 8, 18),
        ('Consider focusing on planting cotton.', 14, 1),
        ('Consider focusing on planting cotton.', 29, 4),
        ('Consider focusing on planting sesame.', 3, 19),
        ('Consider focusing on planting red gram.', 30, 8),
        ('Consider focusing on planting soyabean.', 29, 4),
        ('Decrease the level of irrigation.', 2, 21),
        ('Consider focusing on planting sorghum.', 16, 13),
        ('Consider focusing on planting cotton.', 14, 19),
        ('Invest in heat tolerant varieties.', 25, 23),
        ('Invest in heat tolerant varieties.', 5, 24),
        ('Consider focusing on planting rice.', 26, 4),
        ('Think about utilizing interplanting.', 26, 14),
        ('Consider focusing on planting cotton.', 6, 15),
        ('Consider using biofertilizers.', 32, 8),
        ('Consider using biofertilizers.', 19, 9),
        ('Consider focusing on planting sorghum.', 15, 24),
        ('Consider focusing on planting castor.', 17, 14),
        ('Consider focusing on planting soyabean.', 19, 17),
        ('Invest in heat tolerant varieties.', 3, 18),
        ('Decrease the level of irrigation.', 21, 10),
        ('Think about utilizing interplanting.', 1, 4),
        ('Consider using biofertilizers.', 24, 20),
        ('Consider focusing on planting soyabean.', 5, 11),
        ('Consider using nitrogen.', 10, 8),
        ('Consider focusing on groundnut.', 12, 23),
        ('Invest in heat tolerant varieties.', 7, 13),
        ('Increase the level of irrigation.', 8, 4),
        ('Consider focusing on planting sorghum.', 4, 7),
        ('Consider focusing on planting sesame.', 9, 1),
        ('Consider focusing on planting soyabean.', 23, 6),
        ('Decrease the level of irrigation.', 5, 6),
        ('Consider focusing on planting soyabean.', 25, 11),
        ('Consider using biofertilizers.', 9, 22),
        ('Consider focusing on planting sorghum.', 10, 15),
        ('Consider using nitrogen.', 33, 5),
        ('Consider focusing on planting castor.', 2, 11),
        ('Think about utilizing interplanting.', 21, 16),
        ('Increase the level of irrigation.', 24, 3),
        ('Consider focusing on planting red gram.', 10, 18),
        ('Consider focusing on planting black gram.', 25, 18),
        ('Consider focusing on planting black gram.', 9, 22),
        ('Invest in heat tolerant varieties.', 17, 21),
        ('Invest in heat tolerant varieties.', 4, 1),
        ('Consider using nitrogen.', 26, 1),
        ('Decrease the level of irrigation.', 21, 20),
        ('Consider focusing on planting green gram.', 26, 13),
        ('Consider focusing on planting soyabean.', 1, 21),
        ('Invest in cold tolerant varieties.', 7, 11),
        ('Invest in cold tolerant varieties.', 5, 9),
        ('Consider focusing on planting black gram.', 10, 18),
        ('Consider focusing on planting rice.', 7, 16),
        ('Consider focusing on planting sesame.', 19, 2),
        ('Consider focusing on planting sorghum.', 25, 7),
        ('Think about utilizing interplanting.', 30, 1),
        ('Consider focusing on planting sorghum.', 6, 21),
        ('Consider using nitrogen.', 33, 7),
        ('Consider focusing on planting soyabean.', 20, 17),
        ('Consider focusing on planting red gram.', 18, 1),
        ('Think about utilizing interplanting.', 9, 19),
        ('Invest in heat tolerant varieties.', 19, 21),
        ('Think about utilizing interplanting.', 1, 3),
        ('Consider focusing on planting cotton.', 15, 4),
        ('Consider focusing on planting red gram.', 3, 14),
        ('Consider using biofertilizers.', 7, 18),
        ('Consider focusing on planting castor.', 30, 15),
        ('Consider focusing on planting black gram.', 3, 13),
        ('Increase the level of irrigation.', 5, 12),
        ('Consider focusing on planting green gram.', 16, 24),
        ('Consider focusing on planting rice.', 30, 18),
        ('Consider focusing on planting sesame.', 28, 23),
        ('Consider focusing on planting corn.', 6, 18),
        ('Consider focusing on planting green gram.', 13, 6),
        ('Consider focusing on planting green gram.', 6, 13),
        ('Invest in heat tolerant varieties.', 25, 6),
        ('Consider focusing on planting black gram.', 15, 13),
        ('Increase the level of irrigation.', 30, 7),
        ('Consider focusing on planting green gram.', 10, 19),
        ('Consider focusing on planting black gram.', 3, 20),
        ('Decrease the level of irrigation.', 12, 21),
        ('Invest in heat tolerant varieties.', 7, 9),
        ('Consider focusing on planting sorghum.', 6, 11),
        ('Consider focusing on planting castor.', 25, 20),
        ('Invest in heat tolerant varieties.', 31, 2),
        ('Think about utilizing interplanting.', 15, 23),
        ('Consider using biofertilizers.', 8, 3),
        ('Consider focusing on planting corn.', 28, 17),
        ('Consider focusing on planting red gram.', 10, 9),
        ('Consider using nitrogen.', 18, 24),
        ('Consider focusing on planting soyabean.', 26, 11),
        ('Consider focusing on planting cotton.', 12, 22),
        ('Consider focusing on groundnut.', 7, 15),
        ('Consider using nitrogen.', 2, 1),
        ('Consider focusing on planting castor.', 22, 1),
        ('Consider focusing on planting red gram.', 30, 2),
        ('Consider using nitrogen.', 15, 16),
        ('Invest in heat tolerant varieties.', 10, 13),
        ('Consider focusing on planting soyabean.', 22, 17),
        ('Consider focusing on planting red gram.', 9, 10),
        ('Consider focusing on planting sesame.', 8, 21),
        ('Consider focusing on planting sorghum.', 8, 24),
        ('Decrease the level of irrigation.', 3, 20),
        ('Consider focusing on planting soyabean.', 4, 7),
        ('Consider focusing on planting sesame.', 23, 10),
        ('Consider focusing on planting corn.', 9, 9),
        ('Decrease the level of irrigation.', 18, 4),
        ('Consider focusing on planting cotton.', 2, 5),
        ('Consider focusing on planting castor.', 8, 5),
        ('Consider using biofertilizers.', 31, 21),
        ('Consider focusing on planting castor.', 7, 11),
        ('Consider focusing on planting cotton.', 18, 7),
        ('Consider using biofertilizers.', 17, 3),
        ('Consider focusing on planting sorghum.', 8, 20),
        ('Consider using biofertilizers.', 5, 15),
        ('Consider using nitrogen.', 30, 7),
        ('Increase the level of irrigation.', 30, 11),
        ('Consider focusing on planting soyabean.', 14, 3),
        ('Increase the level of irrigation.', 22, 1),
        ('Consider focusing on planting sorghum.', 33, 9),
        ('Consider focusing on planting sesame.', 12, 14),
        ('Consider focusing on planting sorghum.', 23, 11),
        ('Consider focusing on planting corn.', 2, 10),
        ('Consider focusing on planting castor.', 30, 6),
        ('Think about utilizing interplanting.', 12, 16),
        ('Increase the level of irrigation.', 12, 11),
        ('Consider focusing on planting black gram.', 32, 13),
        ('Consider focusing on planting sesame.', 19, 12),
        ('Invest in heat tolerant varieties.', 24, 16),
        ('Consider focusing on planting sesame.', 8, 12),
        ('Consider focusing on planting green gram.', 27, 1),
        ('Consider focusing on planting corn.', 9, 15),
        ('Consider using nitrogen.', 5, 4),
        ('Increase the level of irrigation.', 22, 18),
        ('Consider focusing on groundnut.', 11, 21),
        ('Consider focusing on groundnut.', 25, 10),
        ('Consider focusing on planting soyabean.', 15, 12),
        ('Consider focusing on planting black gram.', 23, 24),
        ('Consider focusing on planting green gram.', 6, 12),
        ('Consider focusing on planting corn.', 29, 6),
        ('Consider focusing on planting black gram.', 6, 21),
        ('Consider focusing on planting sorghum.', 7, 8),
        ('Think about utilizing interplanting.', 16, 12),
        ('Consider using nitrogen.', 17, 7),
        ('Invest in heat tolerant varieties.', 7, 21),
        ('Consider focusing on planting sorghum.', 25, 8),
        ('Consider focusing on planting sesame.', 26, 19),
        ('Invest in cold tolerant varieties.', 20, 22),
        ('Consider using biofertilizers.', 11, 1),
        ('Consider focusing on planting red gram.', 25, 4),
        ('Consider using biofertilizers.', 8, 5),
        ('Consider focusing on planting corn.', 18, 22),
        ('Consider using nitrogen.', 19, 3),
        ('Consider focusing on planting cotton.', 18, 10),
        ('Consider focusing on planting red gram.', 28, 7),
        ('Consider focusing on planting red gram.', 12, 20),
        ('Consider focusing on planting green gram.', 19, 2),
        ('Consider focusing on planting corn.', 20, 12),
        ('Think about utilizing interplanting.', 4, 23),
        ('Consider focusing on planting red gram.', 25, 1),
        ('Consider focusing on planting corn.', 33, 22),
        ('Consider focusing on planting castor.', 15, 17),
        ('Consider using nitrogen.', 11, 10),
        ('Consider focusing on planting green gram.', 31, 15),
        ('Invest in heat tolerant varieties.', 13, 16),
        ('Consider focusing on planting sorghum.', 17, 15),
        ('Consider using biofertilizers.', 5, 7),
        ('Increase the level of irrigation.', 20, 22),
        ('Invest in cold tolerant varieties.', 14, 18),
        ('Consider focusing on groundnut.', 31, 24),
        ('Increase the level of irrigation.', 16, 2),
        ('Consider focusing on planting green gram.', 19, 7),
        ('Think about utilizing interplanting.', 31, 20),
        ('Think about utilizing interplanting.', 11, 5),
        ('Consider focusing on planting rice.', 22, 23),
        ('Consider focusing on planting green gram.', 23, 8),
        ('Consider focusing on groundnut.', 27, 10),
        ('Consider using biofertilizers.', 33, 7),
        ('Consider focusing on planting soyabean.', 32, 4),
        ('Invest in heat tolerant varieties.', 15, 17),
        ('Consider using biofertilizers.', 26, 22),
        ('Consider focusing on planting green gram.', 19, 15),
        ('Consider focusing on planting corn.', 8, 10),
        ('Decrease the level of irrigation.', 11, 10),
        ('Consider focusing on planting sorghum.', 12, 23),
        ('Consider focusing on planting sesame.', 29, 18),
        ('Invest in cold tolerant varieties.', 31, 6),
        ('Consider focusing on planting green gram.', 23, 10),
        ('Invest in cold tolerant varieties.', 23, 1),
        ('Consider focusing on planting sorghum.', 33, 6),
        ('Increase the level of irrigation.', 22, 14),
        ('Consider focusing on planting green gram.', 17, 12),
        ('Increase the level of irrigation.', 18, 13),
        ('Consider focusing on planting red gram.', 8, 24),
        ('Decrease the level of irrigation.', 16, 18),
        ('Consider focusing on groundnut.', 24, 3),
        ('Consider focusing on groundnut.', 14, 19),
        ('Invest in heat tolerant varieties.', 19, 14),
        ('Consider focusing on planting green gram.', 12, 20),
        ('Consider focusing on planting castor.', 14, 23),
        ('Consider focusing on planting red gram.', 16, 14),
        ('Consider using biofertilizers.', 29, 12),
        ('Consider focusing on planting black gram.', 20, 24),
        ('Increase the level of irrigation.', 25, 2),
        ('Consider focusing on planting black gram.', 32, 9),
        ('Invest in cold tolerant varieties.', 2, 8),
        ('Decrease the level of irrigation.', 7, 16),
        ('Consider focusing on planting castor.', 24, 10),
        ('Consider using nitrogen.', 4, 6),
        ('Consider focusing on planting soyabean.', 9, 4),
        ('Consider focusing on planting red gram.', 18, 11),
        ('Invest in heat tolerant varieties.', 23, 11),
        ('Consider using biofertilizers.', 20, 3),
        ('Consider focusing on planting corn.', 25, 5),
        ('Consider focusing on planting sesame.', 1, 7),
        ('Consider focusing on planting red gram.', 33, 6),
        ('Consider focusing on planting soyabean.', 14, 7),
        ('Consider focusing on planting sorghum.', 8, 19),
        ('Consider focusing on planting sesame.', 20, 24),
        ('Invest in heat tolerant varieties.', 23, 21),
        ('Consider focusing on planting sorghum.', 20, 17),
        ('Consider focusing on planting corn.', 28, 16),
        ('Consider focusing on planting sorghum.', 31, 22),
        ('Consider focusing on groundnut.', 3, 19),
        ('Consider focusing on planting sorghum.', 17, 1),
        ('Invest in heat tolerant varieties.', 25, 3),
        ('Consider focusing on planting castor.', 24, 8),
        ('Consider focusing on planting red gram.', 22, 7),
        ('Consider using nitrogen.', 29, 3),
        ('Consider using biofertilizers.', 33, 11),
        ('Consider focusing on planting sorghum.', 33, 20),
        ('Consider focusing on planting green gram.', 24, 15),
        ('Invest in cold tolerant varieties.', 15, 9),
        ('Consider focusing on planting sesame.', 14, 24),
        ('Consider focusing on planting rice.', 24, 3),
        ('Consider focusing on planting castor.', 25, 4),
        ('Consider focusing on planting green gram.', 16, 13),
        ('Increase the level of irrigation.', 22, 2),
        ('Consider using biofertilizers.', 33, 8),
        ('Consider using biofertilizers.', 29, 11),
        ('Invest in cold tolerant varieties.', 10, 13),
        ('Consider focusing on planting sorghum.', 9, 19),
        ('Increase the level of irrigation.', 10, 23),
        ('Consider focusing on planting green gram.', 18, 2),
        ('Consider using biofertilizers.', 33, 18),
        ('Consider focusing on planting castor.', 24, 14),
        ('Consider focusing on planting sorghum.', 32, 24),
        ('Invest in heat tolerant varieties.', 28, 20),
        ('Consider focusing on planting corn.', 33, 21),
        ('Consider focusing on planting green gram.', 24, 15),
        ('Consider focusing on planting rice.', 18, 17),
        ('Consider focusing on planting green gram.', 27, 6),
        ('Consider focusing on planting sorghum.', 10, 22),
        ('Invest in cold tolerant varieties.', 33, 8),
        ('Consider focusing on planting red gram.', 17, 3),
        ('Consider using biofertilizers.', 28, 13),
        ('Invest in heat tolerant varieties.', 32, 2),
        ('Consider focusing on planting black gram.', 31, 20),
        ('Consider focusing on planting rice.', 25, 18),
        ('Consider focusing on planting castor.', 20, 19),
        ('Consider focusing on planting soyabean.', 27, 2),
        ('Consider focusing on planting castor.', 10, 14),
        ('Consider focusing on planting black gram.', 26, 24),
        ('Consider focusing on planting sorghum.', 9, 5),
        ('Consider focusing on planting sesame.', 32, 5),
        ('Increase the level of irrigation.', 11, 23),
        ('Consider focusing on planting corn.', 33, 7),
        ('Invest in heat tolerant varieties.', 27, 9),
        ('Consider using biofertilizers.', 25, 21),
        ('Consider focusing on planting green gram.', 2, 20),
        ('Consider focusing on planting black gram.', 28, 8),
        ('Consider focusing on planting sorghum.', 32, 11),
        ('Invest in cold tolerant varieties.', 24, 1),
        ('Consider focusing on planting green gram.', 10, 20),
        ('Consider using biofertilizers.', 13, 21),
        ('Decrease the level of irrigation.', 7, 14),
        ('Consider focusing on planting green gram.', 31, 10),
        ('Consider focusing on planting cotton.', 19, 16),
        ('Consider focusing on planting corn.', 7, 9),
        ('Consider focusing on planting green gram.', 5, 16),
        ('Consider focusing on planting corn.', 15, 11),
        ('Consider focusing on planting cotton.', 23, 15),
        ('Invest in heat tolerant varieties.', 20, 3),
        ('Consider focusing on planting rice.', 24, 22),
        ('Consider focusing on planting soyabean.', 25, 10),
        ('Consider using nitrogen.', 13, 4),
        ('Think about utilizing interplanting.', 11, 3),
        ('Consider focusing on planting cotton.', 16, 23),
        ('Think about utilizing interplanting.', 2, 18),
        ('Consider focusing on planting rice.', 16, 15),
        ('Consider focusing on groundnut.', 26, 8),
        ('Consider using nitrogen.', 14, 7),
        ('Consider focusing on planting rice.', 27, 3),
        ('Consider focusing on planting cotton.', 2, 10),
        ('Consider focusing on planting rice.', 33, 19),
        ('Invest in heat tolerant varieties.', 30, 17),
        ('Consider using biofertilizers.', 25, 13),
        ('Increase the level of irrigation.', 17, 2),
        ('Consider focusing on planting cotton.', 27, 20),
        ('Consider using biofertilizers.', 28, 13),
        ('Consider focusing on planting red gram.', 11, 11),
        ('Consider focusing on planting green gram.', 17, 15),
        ('Consider focusing on planting rice.', 6, 22),
        ('Consider using nitrogen.', 3, 4),
        ('Consider focusing on planting green gram.', 19, 20),
        ('Think about utilizing interplanting.', 32, 18),
        ('Consider focusing on planting sorghum.', 20, 7),
        ('Invest in heat tolerant varieties.', 26, 19),
        ('Consider focusing on groundnut.', 10, 8),
        ('Consider focusing on planting green gram.', 12, 12),
        ('Consider focusing on planting castor.', 27, 1),
        ('Consider focusing on planting rice.', 17, 20),
        ('Consider focusing on planting cotton.', 23, 9),
        ('Consider focusing on planting castor.', 18, 17),
        ('Consider focusing on planting rice.', 31, 2),
        ('Invest in cold tolerant varieties.', 21, 8),
        ('Consider using nitrogen.', 12, 6),
        ('Consider focusing on planting black gram.', 10, 2),
        ('Consider focusing on planting castor.', 18, 9),
        ('Consider focusing on groundnut.', 11, 6),
        ('Consider focusing on planting castor.', 32, 17),
        ('Consider focusing on planting castor.', 12, 12),
        ('Decrease the level of irrigation.', 24, 9),
        ('Consider using nitrogen.', 27, 8),
        ('Invest in cold tolerant varieties.', 15, 9),
        ('Consider focusing on planting cotton.', 8, 20),
        ('Increase the level of irrigation.', 2, 17),
        ('Invest in heat tolerant varieties.', 31, 11),
        ('Consider focusing on planting cotton.', 24, 7),
        ('Consider focusing on planting sorghum.', 32, 21),
        ('Consider focusing on planting castor.', 33, 9),
        ('Consider focusing on planting soyabean.', 1, 21),
        ('Consider focusing on planting black gram.', 2, 14),
        ('Consider using biofertilizers.', 2, 8),
        ('Increase the level of irrigation.', 30, 19),
        ('Consider focusing on planting red gram.', 15, 19),
        ('Consider focusing on planting corn.', 1, 7),
        ('Increase the level of irrigation.', 12, 5),
        ('Consider using nitrogen.', 13, 21),
        ('Consider focusing on planting cotton.', 9, 14),
        ('Consider focusing on planting sorghum.', 11, 14),
        ('Think about utilizing interplanting.', 20, 5),
        ('Decrease the level of irrigation.', 33, 2),
        ('Think about utilizing interplanting.', 5, 19),
        ('Think about utilizing interplanting.', 11, 9),
        ('Consider focusing on planting corn.', 29, 10),
        ('Consider focusing on planting corn.', 9, 24),
        ('Decrease the level of irrigation.', 29, 23),
        ('Decrease the level of irrigation.', 13, 17),
        ('Consider focusing on planting red gram.', 5, 19),
        ('Consider focusing on planting castor.', 33, 11),
        ('Invest in heat tolerant varieties.', 33, 20),
        ('Invest in heat tolerant varieties.', 30, 24),
        ('Increase the level of irrigation.', 8, 22),
        ('Invest in heat tolerant varieties.', 2, 18),
        ('Consider focusing on planting cotton.', 26, 22),
        ('Invest in heat tolerant varieties.', 27, 2),
        ('Consider focusing on planting green gram.', 6, 14),
        ('Consider focusing on planting black gram.', 20, 13),
        ('Consider focusing on planting soyabean.', 7, 6),
        ('Decrease the level of irrigation.', 18, 9),
        ('Consider focusing on groundnut.', 19, 3),
        ('Consider focusing on planting sesame.', 13, 8),
        ('Consider focusing on planting sesame.', 3, 6),
        ('Invest in cold tolerant varieties.', 23, 17),
        ('Increase the level of irrigation.', 9, 3),
        ('Consider focusing on planting sorghum.', 6, 1),
        ('Consider focusing on planting red gram.', 9, 24),
        ('Consider focusing on planting corn.', 33, 24),
        ('Decrease the level of irrigation.', 9, 17),
        ('Consider focusing on planting sorghum.', 32, 4),
        ('Think about utilizing interplanting.', 13, 1),
        ('Consider focusing on planting sesame.', 15, 22),
        ('Invest in cold tolerant varieties.', 12, 3),
        ('Consider focusing on planting soyabean.', 6, 12),
        ('Increase the level of irrigation.', 6, 16),
        ('Consider using nitrogen.', 5, 4),
        ('Increase the level of irrigation.', 25, 23),
        ('Invest in heat tolerant varieties.', 33, 19),
        ('Decrease the level of irrigation.', 8, 2),
        ('Consider using biofertilizers.', 3, 22),
        ('Consider using nitrogen.', 23, 14),
        ('Consider focusing on planting sesame.', 2, 20),
        ('Invest in heat tolerant varieties.', 29, 13),
        ('Consider focusing on planting cotton.', 8, 20),
        ('Consider focusing on planting castor.', 9, 15),
        ('Consider using nitrogen.', 20, 16),
        ('Consider using biofertilizers.', 15, 20),
        ('Consider focusing on planting sorghum.', 7, 19),
        ('Invest in cold tolerant varieties.', 6, 2),
        ('Consider focusing on planting sesame.', 28, 17),
        ('Consider using nitrogen.', 14, 14),
        ('Consider focusing on planting sesame.', 12, 21),
        ('Increase the level of irrigation.', 23, 20),
        ('Consider focusing on planting red gram.', 9, 24),
        ('Consider focusing on groundnut.', 23, 21),
        ('Consider focusing on planting sesame.', 16, 21),
        ('Consider focusing on planting sorghum.', 31, 2),
        ('Consider using biofertilizers.', 2, 17),
        ('Increase the level of irrigation.', 13, 5),
        ('Consider using nitrogen.', 18, 16),
        ('Consider focusing on planting sesame.', 17, 12),
        ('Consider focusing on planting red gram.', 18, 9),
        ('Invest in heat tolerant varieties.', 4, 3),
        ('Consider focusing on planting corn.', 21, 12),
        ('Consider focusing on planting rice.', 3, 22),
        ('Consider focusing on planting sorghum.', 25, 16),
        ('Increase the level of irrigation.', 1, 11),
        ('Increase the level of irrigation.', 28, 4),
        ('Consider focusing on planting corn.', 2, 7),
        ('Consider focusing on planting black gram.', 28, 16),
        ('Decrease the level of irrigation.', 32, 20),
        ('Consider focusing on planting castor.', 27, 21),
        ('Consider using nitrogen.', 11, 14),
        ('Consider focusing on planting corn.', 20, 8),
        ('Consider focusing on planting castor.', 29, 10),
        ('Consider using nitrogen.', 11, 6),
        ('Invest in heat tolerant varieties.', 16, 5),
        ('Consider using biofertilizers.', 21, 1),
        ('Consider focusing on planting green gram.', 19, 3),
        ('Consider focusing on planting corn.', 21, 13),
        ('Consider focusing on planting corn.', 6, 6),
        ('Consider focusing on planting green gram.', 31, 13),
        ('Think about utilizing interplanting.', 7, 7),
        ('Consider focusing on planting cotton.', 17, 9),
        ('Consider focusing on planting corn.', 23, 17),
        ('Consider focusing on planting sorghum.', 22, 14),
        ('Consider focusing on planting green gram.', 22, 24),
        ('Consider focusing on planting green gram.', 22, 13),
        ('Consider focusing on planting rice.', 7, 18),
        ('Consider using biofertilizers.', 16, 20),
        ('Consider focusing on planting rice.', 19, 19),
        ('Consider focusing on planting corn.', 13, 13),
        ('Consider focusing on planting soyabean.', 19, 17),
        ('Consider focusing on planting cotton.', 2, 2),
        ('Consider focusing on planting sesame.', 30, 3),
        ('Consider focusing on planting castor.', 6, 10),
        ('Consider focusing on planting cotton.', 28, 9),
        ('Consider focusing on planting sesame.', 32, 8),
        ('Consider focusing on planting rice.', 7, 18),
        ('Consider focusing on groundnut.', 11, 11),
        ('Consider focusing on planting green gram.', 19, 2),
        ('Consider focusing on planting sorghum.', 21, 16),
        ('Invest in cold tolerant varieties.', 10, 22),
        ('Decrease the level of irrigation.', 17, 22),
        ('Increase the level of irrigation.', 13, 15),
        ('Consider focusing on planting sorghum.', 16, 13),
        ('Consider focusing on planting cotton.', 19, 18),
        ('Consider focusing on planting rice.', 2, 20),
        ('Consider focusing on planting green gram.', 6, 9),
        ('Consider using biofertilizers.', 24, 24),
        ('Invest in heat tolerant varieties.', 12, 3),
        ('Consider using nitrogen.', 32, 11),
        ('Consider focusing on planting castor.', 6, 23),
        ('Consider focusing on planting sorghum.', 23, 9),
        ('Consider using nitrogen.', 16, 7),
        ('Decrease the level of irrigation.', 30, 2),
        ('Consider focusing on planting sorghum.', 5, 22),
        ('Consider focusing on planting soyabean.', 2, 4),
        ('Consider focusing on planting green gram.', 15, 5),
        ('Consider focusing on planting red gram.', 2, 20),
        ('Invest in heat tolerant varieties.', 33, 16),
        ('Invest in cold tolerant varieties.', 8, 11),
        ('Invest in cold tolerant varieties.', 21, 14),
        ('Consider using nitrogen.', 15, 20),
        ('Consider focusing on planting soyabean.', 31, 2),
        ('Consider focusing on planting sesame.', 15, 19),
        ('Increase the level of irrigation.', 5, 4),
        ('Consider focusing on planting corn.', 31, 9),
        ('Increase the level of irrigation.', 16, 9),
        ('Consider focusing on planting green gram.', 10, 4),
        ('Consider focusing on planting soyabean.', 16, 18),
        ('Consider focusing on planting red gram.', 13, 17),
        ('Invest in cold tolerant varieties.', 31, 16),
        ('Decrease the level of irrigation.', 32, 14),
        ('Decrease the level of irrigation.', 8, 21),
        ('Consider focusing on planting green gram.', 15, 20),
        ('Consider focusing on planting rice.', 30, 11),
        ('Consider using nitrogen.', 2, 11),
        ('Consider focusing on planting castor.', 27, 21),
        ('Decrease the level of irrigation.', 4, 12),
        ('Consider focusing on planting sesame.', 27, 21),
        ('Consider focusing on planting red gram.', 23, 16),
        ('Consider focusing on planting sorghum.', 33, 8),
        ('Consider focusing on planting red gram.', 21, 21),
        ('Consider focusing on planting cotton.', 32, 8),
        ('Invest in heat tolerant varieties.', 26, 9),
        ('Consider using biofertilizers.', 17, 17),
        ('Invest in heat tolerant varieties.', 11, 3),
        ('Consider focusing on planting black gram.', 6, 9),
        ('Invest in cold tolerant varieties.', 18, 2),
        ('Invest in cold tolerant varieties.', 26, 23),
        ('Decrease the level of irrigation.', 27, 21),
        ('Consider focusing on planting sorghum.', 28, 24),
        ('Consider using nitrogen.', 33, 6),
        ('Consider focusing on planting black gram.', 18, 8),
        ('Consider using biofertilizers.', 15, 4),
        ('Consider using biofertilizers.', 21, 5),
        ('Increase the level of irrigation.', 20, 8),
        ('Invest in heat tolerant varieties.', 31, 19),
        ('Consider focusing on planting sesame.', 20, 10),
        ('Think about utilizing interplanting.', 29, 10),
        ('Consider using nitrogen.', 2, 12),
        ('Consider focusing on planting castor.', 3, 23),
        ('Consider focusing on planting red gram.', 3, 13),
        ('Decrease the level of irrigation.', 27, 10),
        ('Consider focusing on planting green gram.', 25, 23),
        ('Invest in cold tolerant varieties.', 23, 12),
        ('Consider focusing on planting castor.', 7, 5),
        ('Invest in heat tolerant varieties.', 19, 14),
        ('Consider using biofertilizers.', 6, 16),
        ('Consider focusing on planting green gram.', 29, 7),
        ('Consider using nitrogen.', 2, 24),
        ('Consider using nitrogen.', 22, 6),
        ('Increase the level of irrigation.', 4, 22),
        ('Increase the level of irrigation.', 33, 12),
        ('Consider focusing on planting cotton.', 4, 14),
        ('Invest in heat tolerant varieties.', 2, 10),
        ('Invest in heat tolerant varieties.', 11, 19),
        ('Consider focusing on planting corn.', 27, 11),
        ('Consider focusing on planting castor.', 3, 12),
        ('Invest in heat tolerant varieties.', 15, 24),
        ('Consider focusing on groundnut.', 19, 23),
        ('Consider using nitrogen.', 8, 18),
        ('Consider focusing on planting corn.', 12, 21),
        ('Consider focusing on planting black gram.', 27, 20),
        ('Consider focusing on groundnut.', 12, 2),
        ('Consider focusing on planting green gram.', 8, 9),
        ('Consider focusing on planting corn.', 2, 1),
        ('Consider focusing on planting red gram.', 29, 11),
        ('Consider focusing on planting green gram.', 13, 13),
        ('Consider focusing on planting castor.', 22, 7),
        ('Consider focusing on planting sorghum.', 15, 1),
        ('Consider focusing on planting castor.', 16, 16),
        ('Consider using biofertilizers.', 17, 21),
        ('Consider focusing on planting corn.', 14, 13),
        ('Consider focusing on planting rice.', 2, 23),
        ('Consider focusing on planting green gram.', 2, 13),
        ('Consider focusing on planting soyabean.', 7, 13),
        ('Consider focusing on planting rice.', 3, 10),
        ('Consider focusing on planting rice.', 21, 21),
        ('Invest in heat tolerant varieties.', 10, 1),
        ('Think about utilizing interplanting.', 13, 13),
        ('Consider focusing on planting castor.', 8, 5),
        ('Consider focusing on planting soyabean.', 14, 9),
        ('Invest in heat tolerant varieties.', 5, 15),
        ('Consider using nitrogen.', 16, 18),
        ('Invest in heat tolerant varieties.', 32, 4),
        ('Consider focusing on planting black gram.', 5, 2),
        ('Consider focusing on planting sesame.', 24, 6),
        ('Think about utilizing interplanting.', 30, 16),
        ('Consider focusing on planting green gram.', 28, 4),
        ('Invest in heat tolerant varieties.', 30, 5),
        ('Consider focusing on planting cotton.', 20, 13),
        ('Consider focusing on planting black gram.', 17, 14),
        ('Consider focusing on planting sesame.', 10, 6),
        ('Consider focusing on planting black gram.', 8, 22),
        ('Consider focusing on planting sesame.', 18, 1),
        ('Consider focusing on planting sorghum.', 20, 4),
        ('Increase the level of irrigation.', 32, 18),
        ('Consider focusing on planting red gram.', 28, 10),
        ('Consider focusing on planting red gram.', 9, 22),
        ('Consider focusing on groundnut.', 24, 9),
        ('Consider focusing on planting green gram.', 32, 20),
        ('Increase the level of irrigation.', 17, 21),
        ('Consider focusing on planting soyabean.', 31, 22),
        ('Consider focusing on planting black gram.', 7, 17),
        ('Consider using nitrogen.', 32, 19),
        ('Consider focusing on planting black gram.', 2, 24),
        ('Consider focusing on planting sorghum.', 18, 1),
        ('Consider focusing on planting soyabean.', 2, 14),
        ('Consider focusing on planting soyabean.', 24, 11),
        ('Consider focusing on planting castor.', 2, 6),
        ('Consider focusing on planting sesame.', 14, 18),
        ('Consider focusing on planting rice.', 21, 9),
        ('Consider focusing on planting green gram.', 21, 24),
        ('Consider focusing on planting castor.', 17, 9),
        ('Decrease the level of irrigation.', 16, 24),
        ('Consider focusing on planting red gram.', 17, 6),
        ('Decrease the level of irrigation.', 15, 14),
        ('Invest in heat tolerant varieties.', 13, 13),
        ('Consider focusing on planting sorghum.', 16, 21),
        ('Consider focusing on planting sesame.', 15, 15),
        ('Consider focusing on planting sorghum.', 25, 22),
        ('Consider focusing on planting rice.', 5, 6),
        ('Consider focusing on planting cotton.', 26, 16),
        ('Consider focusing on planting black gram.', 9, 12),
        ('Consider focusing on planting corn.', 2, 10),
        ('Invest in cold tolerant varieties.', 17, 19),
        ('Decrease the level of irrigation.', 28, 11),
        ('Consider using biofertilizers.', 5, 18),
        ('Consider focusing on planting red gram.', 26, 7),
        ('Decrease the level of irrigation.', 26, 16),
        ('Consider focusing on planting rice.', 7, 22),
        ('Consider focusing on planting sorghum.', 11, 3),
        ('Consider focusing on groundnut.', 6, 12),
        ('Increase the level of irrigation.', 17, 13),
        ('Consider focusing on planting corn.', 11, 5),
        ('Consider focusing on planting sorghum.', 7, 10),
        ('Consider focusing on planting soyabean.', 2, 23),
        ('Consider focusing on planting soyabean.', 3, 9),
        ('Think about utilizing interplanting.', 26, 1),
        ('Consider using nitrogen.', 19, 23),
        ('Consider focusing on planting soyabean.', 1, 16),
        ('Consider focusing on groundnut.', 32, 8),
        ('Consider focusing on planting soyabean.', 26, 11),
        ('Think about utilizing interplanting.', 18, 1),
        ('Consider using biofertilizers.', 21, 14),
        ('Think about utilizing interplanting.', 17, 7),
        ('Consider using biofertilizers.', 33, 6),
        ('Consider focusing on planting green gram.', 15, 19),
        ('Consider focusing on planting rice.', 28, 24),
        ('Consider focusing on planting rice.', 9, 17),
        ('Consider using nitrogen.', 5, 3),
        ('Consider focusing on groundnut.', 17, 11),
        ('Consider focusing on planting corn.', 9, 15),
        ('Consider focusing on planting cotton.', 25, 15),
        ('Consider using nitrogen.', 13, 13),
        ('Consider focusing on planting corn.', 4, 18),
        ('Think about utilizing interplanting.', 31, 14),
        ('Consider focusing on planting soyabean.', 13, 17),
        ('Consider focusing on groundnut.', 9, 23),
        ('Consider using nitrogen.', 17, 1),
        ('Consider focusing on planting green gram.', 10, 20),
        ('Think about utilizing interplanting.', 6, 9),
        ('Consider using nitrogen.', 31, 11),
        ('Consider focusing on planting castor.', 24, 6),
        ('Consider focusing on planting sesame.', 5, 9),
        ('Consider focusing on planting corn.', 6, 8),
        ('Consider focusing on planting rice.', 7, 3),
        ('Consider focusing on planting castor.', 25, 6),
        ('Consider focusing on planting sorghum.', 9, 13),
        ('Consider focusing on planting sorghum.', 31, 21),
        ('Consider focusing on planting cotton.', 6, 3),
        ('Consider focusing on planting sorghum.', 1, 4),
        ('Consider using biofertilizers.', 14, 6),
        ('Consider focusing on planting sorghum.', 18, 15),
        ('Invest in cold tolerant varieties.', 11, 7);
END IF;
END 
$$