name: Client - build and test

on:
  push:
    tags:
      - v1.*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  system-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test