name: System Tests

on:
  push:
    tags:
      - v1.*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  system-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Code/system_tests/requirements.txt
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
      - name: Run example test
        run: |
          pytest Code/system_tests/example.py
